### PR TITLE
Update phrases.json

### PR DESCRIPTION
**Pull request by yuki0109**

### CODE REVIEW

**Comment by yuki0109** [comment]
Hi tom,
i just added many scripts and press Create new brunch and went the page
because the wifi was not working well.
I afraid all the scripts i put are still in the board..
could you have it look please?
thank you

2015-06-05 18:13 GMT+01:00 Tom Chambers notifications@github.com:

**Comment by tomchambers2** [comment]
All your new stuff is here:
https://github.com/tomchambers2/tinder-art/commit/132841d019fde5911eaf0c4d4e9ce5f57a143530

Is that all of it? I've merged the first lot. Let me know when you're done
with this and I will merge this too.

**Comment by yuki0109** [comment]
Yes, it is all scripts i input today!thank you!

2015-06-05 18:40 GMT+01:00 Tom Chambers notifications@github.com:

> All your new stuff is here:
> 
> https://github.com/tomchambers2/tinder-art/commit/132841d019fde5911eaf0c4d4e9ce5f57a143530
> 
> Is that all of it? I've merged the first lot. Let me know when you're done
> with this and I will merge this too.
>

**Comment by tomchambers2** [comment]
All merged

**Pull request merged**
